name: cfsec
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  cfsec:
    name: cfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: cfsec
        uses: syedhabeebuddin/TestSarif@main
        with:
          sarif_file: 87677786-c120-4f5d-85ed-cc5ea0af6f69.sarif   
          github_token: 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

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: 87677786-c120-4f5d-85ed-cc5ea0af6f69.sarif    
          token: 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
